server:
  port: 9000

spring:
  application:
    name: authorization-server
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:spring-authorization-server-sample
    username: sa
    password: 1234

logging:
  level:
    root: TRACE
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE